# Generated by Django 4.0.4 on 2022-06-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default='admin', verbose_name='Venue Owner'),
        ),
    ]
